---
- hosts: localhost
  connection: local
  tasks:
    - name: Create first virtual network
      azure_rm_virtualnetwork:
        subscription_id: 8e043298-911d-482d-b39a-d83aabe9e445
        resource_group: myResourceGroup
        name: vnet_test
        address_prefixes: "10.0.0.0/16" #CIDR
    - name: Add subnet
      azure_rm_subnet:
        resource_group: myResourceGroup
        name: subnetnet_test
        address_prefix: "10.0.0.0/24"
        virtual_network: vnet_test