---
- hosts: localhost
  connection: local
  tasks:
   - name: Create VM
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: my_VM
    vm_size: Standard_DS1_v2
    admin_username: azureuser
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: <your-key-data>
    network_interfaces: my_NIC
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest




#key_data: az vm create --name my_VM --resource-group myResourceGroup --generate-ssh-keys

