---
- hosts: localhost
  connection: local
  tasks:
  - name: Create a network security group
      azure_rm_securitygroup:
        resource_group: myResourceGroup
        name: my_NSG
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22-23
            access: Allow
            priority: 1001
            direction: Inbound
     