---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a public ip address
      azure_rm_publicipaddress:
        resource_group: myResourceGroup
        name: my_public_ip
        #allocation_method: static
        domain_name: foobar